//generated by ResBuilder in 2014//
#ifndef _RES_H_  
#define _RES_H_  

////StringResID Define Table////
#define  Chinese_Simplified       1   //ºÚÃÂ÷–Œƒ
#define  Chinese_Traditional      2   //∑±ÃÂ÷–Œƒ
#define  Japanese                 3   //»’”Ô
#define  Korean                   4   //∫´”Ô
#define  English                  5   //”¢”Ô
#define  French                   6   //∑®”Ô
#define  German                   7   //µ¬”Ô
#define  Italian                  8   //“‚¥Û¿˚”Ô
#define  Dutch                    9   //∫…¿º”Ô
#define  Portuguese               10  //∆œÃ——¿”Ô
#define  Spanish                  11  //Œ˜∞‡—¿”Ô
#define  Swedish                  12  //»µ‰”Ô
#define  Czech                    13  //Ω›øÀ”Ô
#define  Danish                   14  //µ§¬Û”Ô
#define  Polish                   15  //≤®¿º”Ô
#define  Russian                  16  //∂Ì”Ô
#define  Turkey                   17  //Õ¡∂˙∆‰”Ô
#define  Hebrew                   18  //œ£≤Æ¿¥”Ô
#define  Thai                     19  //Ã©”Ô
#define  Hungarian                20  //–Ÿ—¿¿˚”Ô
#define  Romanian                 21  //¬ﬁ¬Ìƒ·—«”Ô
#define  Arabic                   22  //∞¢¿≠≤Æ”Ô

#define  LANGUAGEID_SUM           22

////BmpResID Define Table////
#define  A0001JL                  1
#define  A0002JL                  2
#define  A0003JL                  3
#define  A0004JL                  4
#define  A0005JL                  5
#define  A0006JL                  6
#define  A0007JL                  7
#define  A0008JL                  8
#define  A0009JL                  9
#define  A0010JL                  10
#define  A0011JL                  11
#define  A0012JL                  12
#define  A0013JL                  13
#define  A0014JL                  14
#define  A0015JL                  15
#define  A0016JL                  16
#define  A0017JL                  17
#define  A0018JL                  18
#define  A0019JL                  19
#define  A0020JL                  20
#define  A0021JL                  21
#define  A0022JL                  22
#define  A0023JL                  23
#define  A0024JL                  24
#define  A0025JL                  25
#define  A0026JL                  26
#define  A0027JL                  27
#define  A0028JL                  28
#define  A0029JL                  29
#define  A0030JL                  30
#define  A0031JL                  31
#define  ACTIVE                   32
#define  ALARM_EN                 33
#define  BT_1                     34
#define  BT_2                     35
#define  BT_CH                    36
#define  BT_CONN                  37
#define  BT_LINK                  38
#define  BT_OFFSET                39
#define  BT_SERH                  40
#define  BT_TA2DP                 41
#define  BT_THFP                  42
#define  BT_THID                  43
#define  BT_TOSET                 44
#define  BT_WAIT                  45
#define  C_NOSEL                  46
#define  C_SEL                    47
#define  CALENDAR1                48
#define  CALENDAR2                49
#define  DEC_FF                   50
#define  DEC_FR                   51
#define  DELLA                    52
#define  DIRROOTA                 53
#define  ECHO                     54
#define  EQCLAS                   55
#define  EQCOUNTRY                56
#define  EQDBB                    57
#define  EQJAZZ                   58
#define  EQNOR                    59
#define  EQPOP                    60
#define  EQROCK                   61
#define  EQSOFT                   62
#define  EQWOW                    63
#define  FM                       64
#define  FMA                      65
#define  FOLDER                   66
#define  FOLDERM                  67
#define  LABA                     68
#define  LABA_NO                  69
#define  LARROW                   70
#define  LINEIN1                  71
#define  LINEIN2                  72
#define  MLOOP1                   73
#define  MLOOP2                   74
#define  MLOOP3                   75
#define  MLOOP4                   76
#define  MLOOP5                   77
#define  MLOOP6                   78
#define  MLOOP7                   79
#define  MUSIC                    80
#define  MUSIC1                   81
#define  OFF_SEL                  82
#define  ON_SEL                   83
#define  PAUSE_EN                 84
#define  PAUSE_IT                 85
#define  PIC_REC                  86
#define  PMDSCOM                  87
#define  PROGRESS                 88
#define  RARROW                   89
#define  REC                      90
#define  RECORD                   91
#define  RECORD1                  92
#define  RECPAUSE                 93
#define  RECSTOP                  94
#define  RN_DOT                   95
#define  RN0                      96
#define  RN1                      97
#define  RN2                      98
#define  RN3                      99
#define  RN4                      100
#define  RN5                      101
#define  RN6                      102
#define  RN7                      103
#define  RN8                      104
#define  RN9                      105
#define  RTC_NUM_0                106
#define  RTC_NUM_1                107
#define  RTC_NUM_2                108
#define  RTC_NUM_3                109
#define  RTC_NUM_4                110
#define  RTC_NUM_5                111
#define  RTC_NUM_6                112
#define  RTC_NUM_7                113
#define  RTC_NUM_8                114
#define  RTC_NUM_9                115
#define  RTC_NUM_A                116
#define  SDMMC                    117
#define  SLIDER_P                 118
#define  SYS_PC                   119
#define  SYS_PC1                  120
#define  SYSTEM1                  121
#define  SYSTEMA                  122
#define  TEST_BIG                 123
#define  TEST_DLI                 124
#define  TEST_EDEL                125
#define  TEST_FLA                 126
#define  TEST_ICON                127
#define  UDISK_PIC                128
#define  UNACTIVE                 129
#define  V_BLOCK                  130
#define  V_SLIDER                 131
#define  V_SLIDER2                132
#define  RESOLUTION               133 //∑÷±Ê¬ 
#define  MENU1                    134 //≤Àµ•1_≤Àµ•1_≤Àµ•1_≤Àµ•1_≤Àµ•1_≤Àµ•
#define  MENU2                    135 //≤Àµ•2
#define  MENU3                    136 //≤Àµ•3
#define  MENU                     137 //≤Àµ•
#define  MENU1_1                  138 //≤Àµ•1_1
#define  MENU1_2                  139 //≤Àµ•1_2

#endif
